import Head from 'next/head'
import CartContainer from '../components/CartContainer'
import Navbar from '../components/Navbar'
import { useSelector, useDispatch } from 'react-redux';
import { calculateTotals } from '../feautures/cart/cartSlice';
import { useEffect } from 'react';
import Modal from '../components/Modal';

export default function Home() {
  const { cartItems } = useSelector((state) => state.cart);

  const dispatch = useDispatch();

  useEffect(() => {
    dispatch(calculateTotals());
  }, [cartItems]);

  const { isOpen } = useSelector((state) => state.modal);

  return (
    <div className="">
      <Head>
        <title>Phone Cart</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {isOpen && <Modal/>}
      <Navbar />
      <CartContainer />
    </div>
  );
}
